name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches: [main]  # Change to your default branch if different (e.g., 'master')

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust based on your Astro version

      - name: Install Dependencies
        run: npm install

      - name: Build Astro Site
        run: npm run build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist  # Change if your build outputs to a different folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1